version: '3.5'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    container_name: postgresProduits
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: nest-docker-postgres-produits
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
