version: '3.5'
services:
  app:
    build: .
    container_name: app-produits
    ports:
      - '3005:3000'
    environment:
      NODE_ENV: production
      PROMETHEUS_PORT: 9100
    env_file:
      - .env.docker
    depends_on:
      - prometheus
    networks:
      - rabbitmq_network

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    container_name: postgresProduits
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - rabbitmq_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus-products
    ports:
      - '9096:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - rabbitmq_network

  grafana:
    image: grafana/grafana
    container_name: grafana-product
    ports:
      - '3002:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - rabbitmq_network
volumes:
  grafana-data:


networks:
  rabbitmq_network:
    name: rabbitmq_network
    external: true
